import layoutStyles from '../../components/Layout/Layout.module.css'
import styles from './SettingsPage.module.css'

export function SettingsPage() {
  return (
    <div className={styles.root}>
      <section className={styles.hero}>
        <div>
          <h2 className={styles.title}>Panel secret & agent onboarding</h2>
          <p className={styles.subtitle}>
            This is a mock UI describing how you will register new agents
            against the unified backend API.
          </p>
        </div>
      </section>

      <section className={layoutStyles.gridFull}>
        <div className={styles.card}>
          <header className={styles.cardHeader}>
            <span className={styles.cardTitle}>Panel secret</span>
          </header>
          <p className={styles.cardBody}>
            In a real deployment, this secret is generated by the backend and
            distributed to your agents. They use it once to register and fetch
            configuration.
          </p>
          <div className={styles.secretRow}>
            <code className={styles.secretValue}>server-panel-dev-xxxxxx</code>
            <button type="button" className={styles.secondaryButton}>
              Copy
            </button>
          </div>
        </div>

        <div className={styles.card}>
          <header className={styles.cardHeader}>
            <span className={styles.cardTitle}>Agent install command</span>
          </header>
          <p className={styles.cardBody}>
            Example bootstrap command that would be executed on a target host
            to install and register an agent with this panel.
          </p>
          <pre className={styles.codeBlock}>
            curl -fsSL https://panel.example.com/install.sh | \
            AGENT_SECRET=server-panel-dev-xxxxxx sh
          </pre>
        </div>
      </section>
    </div>
  )
}

